### ISSUE TITLE
Using with multiple connections

### ISSUE THREAD

**Issue by garak** [dmaicher/doctrine-test-bundle#103]
I use this bundle and it always worked seamlessly with default configuration (e.g. with a single orm/dbal config).
Now I'm trying to add a second connection to a project, that it's working in dev env.
But all my tests are errored, with following:

>Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory

This is a stack trace:
```
/myprj/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
/myprj/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145
/myprj/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:47
/myprj/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php:50
/myprj/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
/myprj/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1185
/myprj/vendor/dama/doctrine-test-bundle/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticConnectionFactory.php:56
/myprj/var/cache/test/ContainerSskoby3/getDoctrine_Dbal_MssqlConnectionService.php:26
/myprj/var/cache/test/ContainerSskoby3/AppTestDebugProjectContainer.php:1084
/myprj/var/cache/test/ContainerSskoby3/getDoctrine_Orm_MssqlEntityManagerService.php:40
/myprj/var/cache/test/ContainerSskoby3/AppTestDebugProjectContainer.php:1084
/myprj/vendor/symfony/dependency-injection/Container.php:304
/myprj/vendor/symfony/doctrine-bridge/ManagerRegistry.php:48
/myprj/vendor/doctrine/common/lib/Doctrine/Common/Persistence/AbstractManagerRegistry.php:231
/myprj/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:49
/myprj/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:52
/myprj/vendor/symfony/http-kernel/Kernel.php:686
/myprj/vendor/symfony/http-kernel/Kernel.php:135
/myprj/vendor/beelab/test-bundle/Test/WebTestCase.php:57
```

**Comment by dmaicher** [comment]
Hmm weird error :confused: 

I'm actually using the bundle on a project with 2 connections without any issues.

Can you share your dbal config?

**Comment by garak** [comment]
Hey, thanks for the prompt  response!

Here it is (with some amendments):

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:APP_DATABASE_URL)%'
                server_version: 5.7
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            mssql:
                url: '%env(resolve:APP_DBMSSQL_URL)%'
                server_version: 14.0.1000

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                mappings:
                   # something probably useless in this context...
            mssql:
                connection: mssql
```
