### ISSUE TITLE
Wrong driver when using DotEnv URL

### ISSUE THREAD

**Issue by ZeusInTexas** [dmaicher/doctrine-test-bundle#117]
Hi,
I just stumbled across an issue with doctrine-test-bundle (awesome work by the way).
Using the following config (note the absence of the `driver` node):

    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'

When creating the connection during container compilation in DoctrineTestCompilerPass, the driver parameter seems to always be set to `pdo_mysql` even if using a non-mysql URL (i.e. `postgres://`), and will fail with the following error when a connection attempt is made:

> Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory

I believe this is related to the issue described in #103. One way to work around this is to set the driver explicitly in the configuration.

**Comment by dmaicher** [comment]
I just tried to test it with a dsn like 

```yaml
doctrine:
    dbal:
        connections:
            default:
                url: 'sqlite:///doctrine_test_bundle.sqlite'
```

and it works fine. So currently I cannot reproduce it :confused: 

What does `bin/console debug:config doctrine` output for this connection?

**Comment by ZeusInTexas** [comment]
I think it's related to later resolution of the environment parameters. When the function is called, `$connectionOptions['url']` looks like `env_<hash omitted>_resolve_DATABASE_URL_<hash omitted>`, and `$connectionOptions['driver']` is set to `pdo_mysql` (the default value).

`bin/console debug:config doctrine` gives:

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: pdo_mysql
                host: localhost
                port: null
                user: root
                password: null
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
        types:
            telephone:
                class: App\CommerceBundle\DBAL\Types\TelephoneType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                query_cache_driver:
                    type: null
                metadata_cache_driver:
                    type: null
                result_cache_driver:
                    type: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                mappings: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

**Comment by dmaicher** [comment]
Not sure its related to this bundle then? When not in the `test` env then this bundle should not even be loaded. And `bin/console debug:config doctrine` uses `dev` env for you I guess?

Ca you try setting the `driver` to null? Like

```yaml
connections:
  default:
    url: '%env(resolve:DATABASE_URL)%'
    driver: ~

**Comment by ZeusInTexas** [comment]
I agree. This might be related to doctrine itself. The bundle is only loaded on test environment as per in `bundles.php`, set by Symfony Flex:

```
DAMA\DoctrineTestBundle\DAMADoctrineTestBundle::class => ['test' => true]
```

Setting driver to null yields

```
In Compiler.php line 108:
                                                                                                 
  Incompatible use of dynamic environment variables "resolve:DATABASE_URL" found in parameters.  
                                                                                                 

In DBALException.php line 107:
                                                                                                                                                                             
  The options 'driver' or 'driverClass' are mandatory if a connection URL without scheme is given to DriverManager::getConnection(). Given URL: %env(resolve:DATABASE_URL)%
```
And `bin/console -e test  debug:config doctrine` gives the same output:
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                host: localhost
                port: null
                user: root
                password: null
                driver: pdo_mysql
                logging: true
                profiling: true
                profiling_collect_backtrace: false
                options: {  }
                mapping_types: {  }
                default_table_options: {  }
                slaves: {  }
                shards: {  }
        types:
            telephone:
                class: App\CommerceBundle\DBAL\Types\TelephoneType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                query_cache_driver:
                    type: null
                metadata_cache_driver:
                    type: null
                result_cache_driver:
                    type: null
                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                quote_strategy: doctrine.orm.quote_strategy.default
                entity_listener_resolver: null
                repository_factory: doctrine.orm.container_repository_factory
                hydrators: {  }
                mappings: {  }
                filters: {  }
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        resolve_target_entities: {  }
```

**Comment by dmaicher** [comment]
I cannot reproduce that. This works for me

```yaml
connections:
  default:
    url: '%env(resolve:DATABASE_URL)%'
    driver: ~
```

```
$ export DATABASE_URL="sqlite:///doctrine_test_bundle.sqlite"
$ bin/console debug:config doctrine | grep 'url:' -A1
                url: '%env(resolve:DATABASE_URL)%'
                driver: null

```
