### ISSUE TITLE
Bundle reuses the same connection for two different underlying connections.

### ISSUE THREAD

**Issue by quentin389** [dmaicher/doctrine-test-bundle#126]
Doctrine Test Bundle incorrectly reuses the same "Static Connection" for two different Symfony/Doctrine connections, which leads to incorrect savepoint management, and can result in "SAVEPOINT DOCTRINE2_SAVEPOINT_2 does not exist" error that is not related to implicit transaction commit.

possible source of the problem: https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/StaticDriver.php#L48

We use two different doctrine connections, with very similar configuration, just so we can flush our logs to the same database, independently of any other transactions / flushes. Doctrine creates two separate physical MySQL connections no matter if their configurations are identical or not. However, this bundle tries to guess if there should be a new connection created, based on a hash computed from connection parameters. If the set of used parameters is identical, the connection is reused, even if underlying Doctrine connection is different. This also happens if the difference in parameters is just in 'schema_filter'.
Example configuration:
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: 5.7
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                schema_filter: ~some values~
            logger:
                server_version: 5.7
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                schema_filter: ~some other values~
```

This leads to a situation when the bundle thinks it's on separate connections, while it's on the same connection. This causes crashes when the secondary connection is used and flushed inside a postUpdate listener for the main connection. In such situation, here is how the savepoint management looks like (info from a simple dump inside `StaticConnection->exec()`):
```
"connection object id: 13776, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 13776, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 13776, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 13776, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_3"
"connection object id: 13776, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_3"
"connection object id: 13776, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 13776, savepoint exec: ROLLBACK TO SAVEPOINT DOCTRINE2_SAVEPOINT_2"
```
which caused an exception, because DOCTRINE2_SAVEPOINT_2 doesn't exist anymore.

Here is how it should look like:
```
"connection object id: 13776, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 15299, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 15299, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_2"
"connection object id: 13776, savepoint exec: SAVEPOINT DOCTRINE2_SAVEPOINT_3"
"connection object id: 13776, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_3"
"connection object id: 13776, savepoint exec: RELEASE SAVEPOINT DOCTRINE2_SAVEPOINT_2"
```

A workaround I have applied:
```
doctrine:
    dbal:
        connections:
            logger:
                ...
                options:
                    fakeOption: someValue
```
which seems to work well for MySQL, but of course it's just a hack.
