### ISSUE TITLE
Not working (no rollback)

### ISSUE THREAD

**Issue by aless673** [dmaicher/doctrine-test-bundle#217]
Maybe i am missing something but nothing is rolledback in this simple test

```
<?php

namespace App\Tests;

use Doctrine\DBAL\Connection;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class TestitTest extends KernelTestCase
{
    private ?Connection $connection;

    public function testSomething(): void
    {
        $this->connection = static::getContainer()->get('doctrine.dbal.default_connection');
        $this->connection->update('user', [
            'lastName' => 'test',
        ], ['id' => 1]);
    }
}
```

extension is enabled

```
    <extensions>
        <extension class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension" />
    </extensions>
```

bundle is enabled 

```
    DAMA\DoctrineTestBundle\DAMADoctrineTestBundle::class => ['test' => true],
```

bundle config

```
dama_doctrine_test:
    enable_static_connection: true
    enable_static_meta_data_cache: true
    enable_static_query_cache: true
```

**Rollback is not working, the data is still changed in DB after test finish : `vendor/bin/phpunit --debug tests/TestitTest.php`**
