### ISSUE TITLE
v8 compiler pass fails due to use_savepoints value

### ISSUE THREAD

**Issue by jdevinemt** [dmaicher/doctrine-test-bundle#274]
I am on Symfony 5.4 and added this bundle to my dev dependencies. It downloaded the latest version at the time of this writing, 8.0.1. When I ran any tests I received the following message, which was coming from the `\DAMA\DoctrineTestBundle\DependencyInjection\DoctrineTestCompilerPass` class:

`LogicException: This bundle relies on savepoints for nested database transactions. You need to enable "use_savepoints" on the Doctrine DBAL config for connection "default".`

I checked the Symfony doctrine config reference for 5.4 (and newer versions), and saw no mention of a `use_savepoints` value. I tried adding it to my doctrine config anyway, but got an error regarding invalid configuration.

```yaml
doctrine:
  dbal:
    connections:
      # example connection name
      main:
        # other config
        use_savepoints: true
```

I ran the following command to check for other configuration possibilities, but it returned no results:
`symfony console config:dump-reference doctrine | grep snapshot`

I removed version "^8" and required version "^7" of this bundle instead and it works fine now.

I am on doctrine/dbal version 3.6.0. Am I trying to configure things incorrectly? If I need to update my config, this `use_savepoints` requirement would be nice to have mentioned in the README.

**Comment by dmaicher** [comment]
You might want to grep for `savepoints` and not `snapshot`? :eyes: 

See for example here where its configured: https://github.com/dmaicher/doctrine-test-bundle/blob/671718004a36d803dc0248ce5b95fb51d748c950/tests/Functional/app/config.yml#L12

What was your error exactly after adding `use_savepoints: true`?

**Comment by jdevinemt** [comment]
Oh boy haha. Turns out I do get `config:dump-reference` results when I'm looking for the right word..

The error I was receiving after updating my doctrine config was the same as the original error.

I use two named connections in my project, one of which I set as the default. So my actual configuration when I originally tested looked something like this:
```yaml
doctrine:
  dbal:
    default_connection: main
    connections:
      main:
        # other config
        use_snapshots: true
      legacy:
        # other config
        use_snapshots: true
```

This still resulted in the exception being thrown regarding the 'default' connection.

But if I update it by adding the default connection explicitly it works:
```yaml
doctrine:
  dbal:
    default_connection: main
    connections:
      main:
        # other config
        use_snapshots: true
      legacy:
        # other config
        use_snapshots: true
      default:
        use_snapshots: true
```

I don't like having to redefine options for my default connection, but maybe there's no way around it.

Most of my confusion came from at some point searching for the term "snapshot" instead of "savepoint" in the docs and in my commands 😅 Thanks for pointing that out and providing this handy package for the community!
